title: Gigi Castro
show_downloads: false
remote_theme: le4ker/personal


description: Computer Science Graduate Student | Data Science | Consumer Behavior
url: "https://gigicastro.github.io"
baseurl: ""

plugins:
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-remote-theme

