title: Gigi Castro
show_downloads: false
theme: jekyll-remote-{ Personal }


description: Computer Science Graduate Student | Data Science | Consumer Behavior
url: "https://gigicastro.github.io/"
baseurl: ""



