theme: jekyll-theme-cayman
title: Gigi Castro 
description: Computer Science Graduate Student | Data Science | Consumer Behavior
baseurl: "/Personal-Portfolio"

show_downloads: false
github:
  is_project_page: false

exclude:
  - README.md
